Repository metwork-framework/mfadmin, pull requests merged in 2018-12, with the labels that each got.

#32 feat: better system dashboard (add diskio stats)
  config/grafana_dashboards/system.json
Labels: Merge Now, Status: Pending

#34 feat: add influxdb local monitoring
  config/telegraf.conf.custom
Labels: Status: Review Needed

#33 feat: add a first version of telegraf dashboard
  config/grafana_dashboards/telegraf.json
Labels: Merge Now, Status: Review Needed

#35 build: fix a commit about telegraf monitoring influxdb
  config/telegraf.conf.custom
Labels: Merge Now, Status: Review Needed

#36 feat: add influxdb system monitoring
  config/telegraf.conf.custom
Labels: Status: Review Needed

#37 build: new dashboard with netio informations
  config/grafana_dashboards/system.json
Labels: Merge Now, Status: Review Needed

#38 Add new monitoring layer from mfext
  layers/layer9_default/.layerapi2_dependencies
Labels: Merge Now, Status: Pending

#39 feat: influxdb upgrade (=>1.7.2)
  layers/layer1_monitoring/0020_influxdb/Makefile.mk
  layers/layer1_monitoring/0020_influxdb/sources
Labels: Status: Review Needed

#40 feat: better mfserv dashboard
  config/grafana_dashboards/mfserv.json
Labels: Merge Now, Status: Review Needed

#41 feat: better mfdata dashboard
  config/grafana_dashboards/mfdata.json
Labels: Merge Now, Status: Pending

#42 feat: better system dashboard
  config/grafana_dashboards/system.json
Labels: Merge Now, Status: Review Needed

#44 build: add missing dependencies file
  layers/layer1_monitoring/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed
