Repository metwork-framework/mfadmin, pull requests merged in 2019-04, with the labels that each got.

#56 addons grafana dashboard
  adm/before_start_grafana
  config/grafana_provisioning/dashboards/dashboard.yaml
Labels: Status: Review Needed, backport-to-0.6

#58 feat: introduce mflog indices rotation
  adm/elasticsearch.clean
Labels: Merge Now, Status: Review Needed

#60 feat: influxdb and grafana update
  config/grafana.ini
  layers/layer1_metrics/0020_influxdb/Makefile.mk
  layers/layer1_metrics/0020_influxdb/sources
  layers/layer1_metrics/0030_grafana/Makefile.mk
  layers/layer1_metrics/0030_grafana/sources
Labels: Status: Review Needed

#62 feat: remove "CPU usage single core" from system dashboard overview
  config/grafana_dashboards/system.json
Labels: Status: Review Needed

#63 feat: monitor influxdb db size
  config/telegraf.conf.custom
Labels: Merge Now, Status: Review Needed

#65 feat: add debug message in case of mfadmin.init silent crash
  adm/mfxxx.init.custom
Labels: Merge Now, Status: Review Needed

#61 Issue59
  adm/Makefile
  adm/_make_nginx_conf
  adm/mfxxx.status.custom
  config/Makefile
  config/circus.ini.custom
  config/config.ini
  config/kibana.conf
  config/nginx.conf
  layers/layer1_logs/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#67 feat: add ES template for mflog
  adm/Makefile
  adm/_provision_mflog_template.py
  adm/mfxxx.init.custom
Labels: Status: Review Needed

#69 feat: add ES datasources in grafana provisionning
  config/grafana_provisioning/datasources/datasource.yaml
Labels: Status: Review Needed

#70 feat: add kibana dashboards import/export/provisionning
  adm/Makefile
  adm/_provision_kibana_dashboards
  adm/_provision_nginx_template.py
  adm/before_start_kibana
  adm/export_kibana_dashboard.py
  adm/import_kibana_dashboard.py
  adm/mfxxx.init.custom
  config/Makefile
  config/kibana_dashboards/mflog1.json
  config/kibana_dashboards/nginx1.json
  config/kibana_dashboards/nginx2.json
Labels: Merge Now, Status: Review Needed

#71 build: remove python3 prerequirement files (useless now)
  layers/layer5_python3/0500_extra_packages/prerequirements-to-freeze.txt
  layers/layer5_python3/0500_extra_packages/prerequirements3.txt
Labels: Merge Now, Status: Revision Needed

#72 feat: kibana dashboard update
  config/kibana_dashboards/mflog1.json
  config/kibana_dashboards/nginx1.json
  config/kibana_dashboards/nginx2.json
Labels: Merge Now, Status: Review Needed

#73 fix: set kibana default index
  adm/_provision_kibana_dashboards
Labels: Merge Now, Status: Review Needed

#74 feat: drop es indices after changing es mapping
  adm/_provision_mflog_template.py
  adm/_provision_nginx_template.py
Labels: Merge Now, Status: Review Needed
