Repository metwork-framework/mfadmin, pull requests merged in 2019-10, with the labels that each got.

#106 build: add components list
  .metwork-framework/components.md
Labels: Merge Now, Status: Review Needed

#107 feat: build mfadmin without mfcom (mfcom layers are now included in m…
  .gitignore
  .layerapi2_dependencies
  adm/Makefile
  adm/_make_nginx_conf
  config/Makefile
  doc/conf.py
  doc/mfadmin_miscellaneous.md
  layer_custom.md
  layers/layer9_default/.layerapi2_dependencies
Labels: Merge Now

#112 fix: tmp fix for #111 (upstream grafana/firefox issue)
  layers/layer1_metrics/0030_grafana/Makefile.mk
Labels: Status: Review Needed, backport-to-0.8, backport-to-0.9

#115 feat: better mfdata dashboard
  config/grafana_dashboards/mfdata.json
Labels: Merge Now, Status: Review Needed, backport-to-0.9

#118 fix: access to grafana when logs layer is not installed
  adm/mfxxx.status.custom
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed, backport-to-0.9
