Repository metwork-framework/mfadmin, pull requests merged in 2019-05, with the labels that each got.

#76 feat: Add a dashboard for mfbase
  config/grafana_dashboards/mfbase.json
Labels: Status: Review Needed

#78 build: remove python layer
  layers/layer9_python/.layerapi2_dependencies
  layers/layer9_python/.layerapi2_label
  layers/layer9_python/Makefile
Labels: Merge Now, Status: Review Needed

#79 Update MFADMIN documentation
  .gitignore
  bootstrap.sh
  doc/Makefile
  doc/_static/css/override_theme.css
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.rst
  doc/conf.py
  doc/images/logo-metwork.png
  doc/images/metwork.ico
  doc/index.rst
  doc/todo.rst
  layer_custom.md
  layers/layer1_logs/layer_custom.md
  layers/layer1_metrics/layer_custom.md
  layers/layer5_python3/layer_custom.md
  layers/layer9_default/layer_custom.md
Labels: Status: Review Needed

#80 build: remove useless python3 layer
  layers/layer5_python3/.layerapi2_dependencies
  layers/layer5_python3/.layerapi2_label
  layers/layer5_python3/0500_extra_packages/Makefile
  layers/layer5_python3/0500_extra_packages/Makefile.mk
  layers/layer5_python3/0500_extra_packages/requirements-to-freeze.txt
  layers/layer5_python3/0500_extra_packages/requirements3.txt
  layers/layer5_python3/Makefile
  layers/layer5_python3/layer_custom.md
  layers/layer9_default/.layerapi2_dependencies
Labels: Merge Now, Status: Review Needed

#81 docs: fix invalid generated images link url
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/conf.py
Labels: Status: Review Needed

#82 build: gitignore fix
  .gitignore
Labels: Merge Now, Status: Review Needed

#83 feat: dashboards update
  config/grafana_dashboards/home.json
  config/grafana_dashboards/mfbase.json
  config/grafana_dashboards/redis.json
  config/kibana_dashboards/mflog1.json
  config/kibana_dashboards/nginx1.json
  config/kibana_dashboards/nginx2.json
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#85 feat: use envtpl new option --reduce-multi-blank-lines
  adm/before_start_elasticsearch
  adm/before_start_grafana
  adm/before_start_influxdb
  adm/before_start_kibana
  config/Makefile
  doc/Makefile
Labels: Status: Review Needed
