Repository metwork-framework/mfadmin, pull requests merged in 2019-06, with the labels that each got.

#88 docs: Update MFADMIN documentation
  .gitignore
  doc/Makefile
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/overall_architecture.svg
  doc/changelogs.tmpl
  doc/conf.py
  doc/index.rst
  doc/mfadmin_intro.md
  doc/mfadmin_miscellaneous.md
  doc/mfadmin_monitoring_plugins.md
  doc/src/overall_architecture.graphml
  layers/layer1_logs/layer_custom.md
  layers/layer1_metrics/layer_custom.md
Labels: Status: Review Needed

#91 docs: Update MFADMIN documentation
  doc/_images/grafana_mfbase_dashboard.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/_images/overall_architecture.svg
  doc/changelogs.rst
  doc/index.rst
  doc/mfadmin_intro.md
  doc/mfadmin_miscellaneous.md
  doc/mfadmin_monitoring_plugins.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#90 feat: add some smtp options for grafana
  config/config.ini
  config/grafana.ini
Labels: Status: Review Needed, backport-to-0.7

#93 docs: Update MFADMIN documentation
  doc/_images/grafana_resolution_dashboard.jpg
  doc/_images/kibana_available_dashboards.jpg
  doc/_images/kibana_edit_visu1.jpg
  doc/_images/kibana_edit_visu2.jpg
  doc/_images/kibana_edit_visu3.jpg
  doc/_images/kibana_mflog_logs_dashboard.jpg
  doc/_images/kibana_nginx_logs_dashboard.jpg
  doc/_images/overall_architecture.svg
  doc/conf.py
  doc/mfadmin_intro.md
  doc/mfadmin_miscellaneous.md
  doc/mfadmin_monitoring_plugins.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#94 docs: Update MFADMIN documentation
  doc/_images/grafana_queries_datasources.jpg
  doc/_images/overall_architecture.svg
  doc/mfadmin_monitoring_plugins.md
  doc/src/overall_architecture.graphml
Labels: Status: Review Needed

#95 feat: better mfserv dashboard
  config/grafana_dashboards/mfserv.json
Labels: Status: Review Needed, backport-to-0.7

#96 feat: send mfadmin mflog logs to itself
  config/circus.ini.custom
Labels: Merge Now, Status: Review Needed, backport-to-0.7

#99 Experimental
  bootstrap.sh
Labels: Merge Now, Status: Review Needed
