Repository metwork-framework/mfadmin, pull requests merged in 2020-09, with the labels that each got.

#151 build: fix doc build
  .gitignore
  doc/Makefile
Labels: Status: Merge Now

#153 build: new docs
  docs/.pages
  docs/010-whatis.md
  docs/950-old_docs/mfadmin_intro.md
  docs/950-old_docs/mfadmin_miscellaneous.md
  docs/950-old_docs/mfadmin_monitoring_plugins.md
  docs/images/grafana_home.jpg
  docs/images/grafana_login.jpg
  docs/images/grafana_mfbase_dashboard.jpg
  docs/images/grafana_mfdata_dashboard.jpg
  docs/images/grafana_queries_datasources.jpg
  docs/images/grafana_resolution_dashboard.jpg
  docs/images/kibana_available_dashboards.jpg
  docs/images/kibana_edit_visu1.jpg
  docs/images/kibana_edit_visu2.jpg
  docs/images/kibana_edit_visu3.jpg
  docs/images/kibana_mflog_logs_dashboard.jpg
  docs/images/kibana_nginx_logs_dashboard.jpg
  docs/images/logo-metwork.png
  docs/images/metwork.ico
  docs/images/overall_architecture.svg
Labels: Status: Merge Now, Status: Review Needed

#154 build: remove old docs
  doc/Makefile
  doc/_images/grafana_home.jpg
  doc/_images/grafana_login.jpg
  doc/_images/grafana_mfbase_dashboard.jpg
  doc/_images/grafana_mfdata_dashboard.jpg
  doc/_images/grafana_queries_datasources.jpg
  doc/_images/grafana_resolution_dashboard.jpg
  doc/_images/kibana_available_dashboards.jpg
  doc/_images/kibana_edit_visu1.jpg
  doc/_images/kibana_edit_visu2.jpg
  doc/_images/kibana_edit_visu3.jpg
  doc/_images/kibana_mflog_logs_dashboard.jpg
  doc/_images/kibana_nginx_logs_dashboard.jpg
  doc/_images/logo-metwork.png
  doc/_images/metwork.ico
  doc/_images/overall_architecture.svg
  doc/_static/css/override_theme.css
  doc/_static/empty
  doc/_templates/breadcrumbs.html
  doc/_templates/layout.html
  doc/changelogs.tmpl
  doc/conf.py
  doc/index.rst
  doc/mfadmin_intro.md
  doc/mfadmin_miscellaneous.md
  doc/mfadmin_monitoring_plugins.md
  doc/src/overall_architecture.graphml
  doc/todo.rst
Labels: Status: Merge Now, Status: Review Needed

#158 build: doc refresh
  docs/.pages
  docs/010-whatis.md
  docs/950-old_docs/.pages
  docs/images/screenshot1.png
  docs/images/screenshot2.png
  docs/images/screenshot3.png
Labels: Status: Merge Now, Status: Review Needed, backport-to-1.0

#168 docs: Update old docs
  docs/950-old_docs/mfadmin_intro.md
  docs/950-old_docs/mfadmin_miscellaneous.md
  docs/950-old_docs/mfadmin_monitoring_plugins.md
Labels: Status: Review Needed, backport-to-1.0
