Repository metwork-framework/mfadmin, pull requests merged in 2021-05, with the labels that each got.

#190 build: fix influxdb download url
  layers/layer1_metrics/0020_influxdb/Makefile.mk
  layers/layer1_metrics/0020_influxdb/sources
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#193 build: update workflows (from common files)
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
Labels: Status: Merge Now, Status: Review Needed

#194 build: update ci.yml (add step mageia repo)
  .github/workflows/ci.yml
Labels: Status: Merge Now

#195 fix: add missing layer dependency
  .layerapi2_dependencies
Labels: Status: Review Needed, backport-to-1.0, backport-to-1.1

#196 fix: fix grafana password
  adm/_force_grafana_admin_password.sh
  adm/grafana.status
Labels: Status: Review Needed, backport-to-1.1

#200 build: CI under github actions
  .github/workflows/ci.yml
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#201 build: CI under github actions
  .drone.yml
  .github/workflows/bootstrap_ci.sh
  .github/workflows/build.sh
  .github/workflows/ci.yml
  .github/workflows/createrepo.sh
  .github/workflows/integration_tests.sh
  .github/workflows/set_variables.sh
Labels: Status: Merge Now

#202 fix: update timeouts for xxx.status
  adm/es.status
  adm/grafana.status
  adm/influxdb.status
  adm/kibana.status
  adm/loki.status
Labels: Status: Review Needed, backport-to-1.1
