Repository metwork-framework/mfadmin, pull requests merged in 2021-02, with the labels that each got.

#185 fix: fix some start/stop issues
  adm/Makefile
  adm/_wait_es.py
  adm/_wait_influxdb.py
  adm/_wait_kibana.py
  adm/es.status
  adm/grafana.status
  adm/influxdb.status
  adm/kibana.status
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
  config/circus.ini.custom
Labels: Status: Review Needed, backport-to-1.0

#187 feat: grafana update
  .metwork-framework/components.md
  config/grafana.ini
  layers/layer1_metrics/0030_grafana/Makefile.mk
  layers/layer1_metrics/0030_grafana/sources
Labels: Status: Review Needed

#188 build: changes for vector usage
  config/Makefile
  config/circus.ini.custom
Labels: Status: Review Needed

#182 feat: add loki and promtail
  .metwork-framework/components.md
  adm/Makefile
  adm/before_start_loki
  adm/loki.status
  adm/mfxxx.start.custom
  adm/mfxxx.status.custom
  adm/mfxxx.stop.custom
  adm/profile.custom
  config/Makefile
  config/circus.ini.custom
  config/config.ini.custom
  config/grafana_provisioning/datasources/datasource.yaml
  config/loki/loki-config.yaml
  layers/layer2_logs_loki/.layerapi2_dependencies
  layers/layer2_logs_loki/.layerapi2_extra_env
  layers/layer2_logs_loki/.layerapi2_label
  layers/layer2_logs_loki/0050_loki/Makefile
  layers/layer2_logs_loki/0050_loki/Makefile.mk
  layers/layer2_logs_loki/0050_loki/sources
  layers/layer2_logs_loki/0100_logcli/Makefile
  layers/layer2_logs_loki/0100_logcli/Makefile.mk
  layers/layer2_logs_loki/0100_logcli/sources
  layers/layer2_logs_loki/Makefile
  layers/layer2_logs_loki/layer_custom.md
  layers/layer9_default/.layerapi2_dependencies
Labels: Status: Revision Needed
