Repository metwork-framework/mfadmin, pull requests merged in 2023-04, with the labels that each got.

#253 fix: metwork version 1.1 hardcoded in _force_grafana_admin_password (…
  adm/_force_grafana_admin_password.sh
Labels: Status: Review Needed, backport-to-1.2, backport-to-2.0, backport-to-2.1

#258 fix: kibana LDAP authent and HTTP Basic authentication (#245)
  config/nginx.conf
Labels: Status: Review Needed, backport-to-2.1

#261 feat: upgrade grafana to 8.5.22 and kibana & elasticsearch to 6.8.23
  .metwork-framework/components.md
  adm/before_start_kibana
  config/config.ini.custom
  config/elasticsearch_jvm_options.conf
  config/kibana.conf
  layers/layer1_logs/0050_elasticsearch/Makefile.mk
  layers/layer1_logs/0050_elasticsearch/sources
  layers/layer1_logs/0060_kibana/Makefile.mk
  layers/layer1_logs/0060_kibana/sources
  layers/layer1_metrics/0030_grafana/Makefile.mk
  layers/layer1_metrics/0030_grafana/sources
Labels: Status: Merge Now
